# Generated by Django 5.2.3 on 2025-06-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_reviews', '0003_remove_restaurant_image_url_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
